In [3]:
import pandas as pd
from torch.utils.data import DataLoader
from data_builder import DataBuilder
from utils import*

In [1]:
data_path = '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/data_nature_filtered.csv'

In [4]:
nature_filtered = pd.read_csv(data_path)
nature_filtered

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y2_Wheel_AvgDistLFC,Y3_Wheel_AvgDistLFC,Y1A_Grip_All,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet
0,DO-40-2162,28,1611,24.787142,26.993230,23.645309,164.713839,134.572768,74.479328,499.174601,...,1.716889,4.448401,89.962669,168.389945,179.558615,0.032865,0.133616,0.159587,1,40
1,DO-40-2179,28,1557,30.432753,23.594599,23.529931,161.043852,71.901384,69.226421,495.841743,...,0.348339,0.747802,291.910043,181.741358,208.833723,0.183285,0.231782,0.235033,1,40
2,DO-40-2181,28,1533,20.747600,19.072890,20.528352,161.043852,93.048894,60.575167,520.949018,...,0.204999,0.192929,221.922043,204.078358,158.799723,0.069442,0.231782,0.197085,1,40
3,DO-40-2187,28,1520,25.977819,29.254446,30.242503,127.747193,85.358891,71.148922,466.210754,...,1.146192,0.924488,145.679543,223.139358,208.833223,0.106295,0.174654,0.216059,1,40
4,DO-40-2099,26,1638,24.242912,23.626717,22.912834,166.520150,72.692867,59.960123,464.789558,...,1.776962,2.179152,261.760471,173.953709,153.357082,0.110173,0.155822,0.285573,1,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,DO-AL-0009,22,349,21.131405,NaN,NaN,140.940870,NaN,NaN,491.072949,...,NaN,NaN,250.583787,NaN,NaN,NaN,NaN,NaN,5,AL
933,DO-1D-3015,22,309,30.660285,NaN,NaN,152.928679,NaN,NaN,NaN,...,NaN,NaN,163.396287,NaN,NaN,NaN,NaN,NaN,4,1D
934,DO-2D-4010,22,309,20.517814,NaN,NaN,144.277424,NaN,NaN,NaN,...,NaN,NaN,173.202287,NaN,NaN,NaN,NaN,NaN,3,2D
935,DO-1D-3006,22,244,26.757601,NaN,NaN,112.556159,NaN,NaN,NaN,...,NaN,NaN,104.987287,NaN,NaN,NaN,NaN,NaN,4,1D


In [5]:
nature_filtered_nonan = set_nans_extreme(nature_filtered)
nature_filtered_nonan

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y2_Wheel_AvgDistLFC,Y3_Wheel_AvgDistLFC,Y1A_Grip_All,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet
0,DO-40-2162,28,1611,24.787142,26.993230,23.645309,164.713839,134.572768,74.479328,499.174601,...,1.716889,4.448401,89.962669,168.389945,179.558615,0.032865,0.133616,0.159587,1,40
1,DO-40-2179,28,1557,30.432753,23.594599,23.529931,161.043852,71.901384,69.226421,495.841743,...,0.348339,0.747802,291.910043,181.741358,208.833723,0.183285,0.231782,0.235033,1,40
2,DO-40-2181,28,1533,20.747600,19.072890,20.528352,161.043852,93.048894,60.575167,520.949018,...,0.204999,0.192929,221.922043,204.078358,158.799723,0.069442,0.231782,0.197085,1,40
3,DO-40-2187,28,1520,25.977819,29.254446,30.242503,127.747193,85.358891,71.148922,466.210754,...,1.146192,0.924488,145.679543,223.139358,208.833223,0.106295,0.174654,0.216059,1,40
4,DO-40-2099,26,1638,24.242912,23.626717,22.912834,166.520150,72.692867,59.960123,464.789558,...,1.776962,2.179152,261.760471,173.953709,153.357082,0.110173,0.155822,0.285573,1,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
932,DO-AL-0009,22,349,21.131405,63.024938,67.590983,140.940870,255.344186,261.476515,491.072949,...,-6.656427,-2.736010,250.583787,66.013018,58.352082,0.301015,0.480959,0.555556,5,AL
933,DO-1D-3015,22,309,30.660285,63.024938,67.590983,152.928679,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,163.396287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D
934,DO-2D-4010,22,309,20.517814,63.024938,67.590983,144.277424,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,173.202287,66.013018,58.352082,0.301015,0.480959,0.555556,3,2D
935,DO-1D-3006,22,244,26.757601,63.024938,67.590983,112.556159,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,104.987287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D


In [6]:
train_set = DataBuilder(nature_filtered_nonan)
test_set = DataBuilder(nature_filtered_nonan)
train_loader = DataLoader(train_set, batch_size=32, shuffle=True)
test_loader = DataLoader(test_set, batch_size=937, shuffle=True)

In [16]:
test_data, test_labels, df_layer1, mouse_ids = next(iter(test_loader))
test_labels[800:805]

tensor([0, 4, 4, 4, 2])

In [17]:
mouse_ids[800:805]

('DO-40-2144', 'DO-AL-0102', 'DO-AL-0154', 'DO-AL-0186', 'DO-2D-4008')

In [18]:
mask = nature_filtered_nonan['MouseID'].isin(mouse_ids[800:805])
diets = nature_filtered_nonan.loc[mask, ['MouseID', 'Diet_num']]
diets

,MouseID,Diet_num
219,DO-AL-0102,5
277,DO-40-2144,1
312,DO-AL-0186,5
560,DO-AL-0154,5
924,DO-2D-4008,3


## Test data loading for the MLP

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, train_test_split
from torch.utils.data import TensorDataset, DataLoader, random_split, SubsetRandomSampler
import torch

In [27]:
data_path = '/Users/racheliritani/Desktop/AD Project/mm-vae/cfc/vanilla_vae_2dim/latent_variables_1000epochs.csv'
cfc_path = '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/cfc_data_filtered.csv'
data_type = 'latent'
label_type = 'cfc'
latent_dim = 2

In [32]:
data_df = pd.read_csv(data_path)
cfc_df = pd.read_csv(cfc_path)
if data_type == 'latent':
    dataset = pd.merge(data_df, cfc_df, left_on='mouse_ids', right_on='Mouse.ID')
elif data_type == 'full':
    dataset = pd.merge(data_df, cfc_df, left_on='MouseID', right_on='Mouse.ID')
dataset

,LV1,LV2,labels,mouse_ids,Diet,Mouse.ID,CFC.24mo.Average
0,1.173299,-0.712594,0,DO-40-2162,40,DO-40-2162,3.78
1,1.540636,-0.721987,0,DO-40-2179,40,DO-40-2179,26.71
2,0.396246,-0.688081,0,DO-40-2181,40,DO-40-2181,27.02
3,0.847429,-0.120307,0,DO-40-2187,40,DO-40-2187,50.40
4,0.212872,0.386063,0,DO-40-2099,40,DO-40-2099,34.18
...,...,...,...,...,...,...,...
499,-1.930858,-1.323612,2,DO-2D-4007,2D,DO-2D-4007,23.69
500,-2.765639,-0.168656,3,DO-1D-3030,1D,DO-1D-3030,29.78
501,-1.197938,-1.281062,1,DO-20-1021,20,DO-20-1021,18.22
502,0.090330,0.025564,4,DO-AL-0002,AL,DO-AL-0002,57.42


In [25]:
ground_truth = '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/nature_filtered_nonan_cfc.csv'
all_data_with_cfc = pd.read_csv(ground_truth)

In [37]:
all_data_with_cfc

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y2_Wheel_AvgDistLFC,Y3_Wheel_AvgDistLFC,Y1A_Grip_All,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet
0,DO-40-2162,28,1611,24.787142,26.993230,23.645309,164.713839,134.572768,74.479328,499.174601,...,1.716889,4.448401,89.962669,168.389945,179.558615,0.032865,0.133616,0.159587,1,40
1,DO-40-2179,28,1557,30.432753,23.594599,23.529931,161.043852,71.901384,69.226421,495.841743,...,0.348339,0.747802,291.910043,181.741358,208.833723,0.183285,0.231782,0.235033,1,40
2,DO-40-2181,28,1533,20.747600,19.072890,20.528352,161.043852,93.048894,60.575167,520.949018,...,0.204999,0.192929,221.922043,204.078358,158.799723,0.069442,0.231782,0.197085,1,40
3,DO-40-2187,28,1520,25.977819,29.254446,30.242503,127.747193,85.358891,71.148922,466.210754,...,1.146192,0.924488,145.679543,223.139358,208.833223,0.106295,0.174654,0.216059,1,40
4,DO-40-2099,26,1638,24.242912,23.626717,22.912834,166.520150,72.692867,59.960123,464.789558,...,1.776962,2.179152,261.760471,173.953709,153.357082,0.110173,0.155822,0.285573,1,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,DO-2D-4007,22,771,40.141463,46.980545,67.590983,112.556159,165.312618,261.476515,554.545551,...,1.715710,-2.736010,206.457287,161.382753,58.352082,0.301015,0.209083,0.555556,3,2D
500,DO-1D-3030,22,748,24.315156,29.916707,67.590983,139.326564,136.439061,261.476515,544.317015,...,0.934841,-2.736010,223.713073,138.051810,58.352082,0.301015,0.082493,0.555556,4,1D
501,DO-20-1021,22,738,30.809768,38.120260,67.590983,168.911742,152.502965,261.476515,542.558402,...,1.218057,-2.736010,194.721573,162.770810,58.352082,0.301015,0.224366,0.555556,2,20
502,DO-AL-0002,22,755,30.261862,48.841393,67.590983,139.018370,125.113095,261.476515,477.144237,...,3.236146,-2.736010,139.520787,117.007253,58.352082,0.301015,0.277963,0.555556,5,AL


In [36]:
dataset.loc[400:405, ['mouse_ids', 'labels']]

,mouse_ids,labels
400,DO-1D-3011,3
401,DO-40-2086,0
402,DO-2D-4023,2
403,DO-40-2093,0
404,DO-1D-3063,3
405,DO-40-2063,0


In [38]:
mask = all_data_with_cfc['MouseID'].isin(dataset.loc[400:405, 'mouse_ids'])
diets = all_data_with_cfc.loc[mask, ['MouseID', 'Diet_num']]
diets

,MouseID,Diet_num
400,DO-1D-3011,4
401,DO-40-2086,1
402,DO-2D-4023,3
403,DO-40-2093,1
404,DO-1D-3063,4
405,DO-40-2063,1


In [40]:
original_starting_data = pd.read_csv('/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/data_nature_filtered.csv')

In [43]:
mask2 = original_starting_data['MouseID'].isin(dataset.loc[400:405, 'mouse_ids'])
diets = original_starting_data.loc[mask2, ['MouseID', 'Diet']]
diets

,MouseID,Diet
588,DO-1D-3011,1D
591,DO-40-2086,40
592,DO-2D-4023,2D
595,DO-40-2093,40
596,DO-1D-3063,1D
597,DO-40-2063,40


In [48]:
latent_dims = 5
latent_columns = [f'LV{i+1}' for i in range(latent_dims)]
latent_columns = latent_columns +  ['labels']

In [49]:
latent_columns

['LV1', 'LV2', 'LV3', 'LV4', 'LV5', 'labels']

In [59]:
data_path = '/Users/racheliritani/Desktop/AD Project/mm-vae/cfc/vanilla_vae_5dim/latent_variables_1000epochs.csv'
cfc_path = '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/cfc_data_filtered.csv'
latent_dim=5
data_df = pd.read_csv(data_path)
cfc_df = pd.read_csv(cfc_path)
if data_type == 'latent':
    dataset = pd.merge(data_df, cfc_df, left_on='mouse_ids', right_on='Mouse.ID')
elif data_type == 'full':
    dataset = pd.merge(data_df, cfc_df, left_on='MouseID', right_on='Mouse.ID')
if label_type == 'cfc': 
    label_col = 'CFC.24mo.Average'
elif label_type == 'ymaze_distance':
    label_col = 'Ymaze.Distance.10mo'
elif label_type == 'ymaze_speed':
    label_col = 'Ymaze.MeanSpeed.10mo'
elif label_type == 'ymaze_alt':
    label_col = 'SpontaneousAlternations.10mo'
train_df, test_df = train_test_split(dataset, test_size=0.2, random_state=42)
scaler = StandardScaler()
if data_type == 'latent':
    latent_columns = [f'LV{i+1}' for i in range(latent_dim)]
elif data_type == 'full':
    latent_columns = ['Generation', 'SurvDays', 'Y1_CBC_Hgb', 'Y2_CBC_Hgb', 'Y3_CBC_Hgb', 'Y1_Rotarod_Mean', 'Y2_Rotarod_Mean', 'Y3_Rotarod_Mean', 'Y1_Wheel_AvgSpeedLFC', 'Y2_Wheel_AvgSpeedLFC', 'Y3_Wheel_AvgSpeedLFC', 'Y1_Wheel_AvgDistLFC', 'Y2_Wheel_AvgDistLFC', 'Y3_Wheel_AvgDistLFC', 'Y1A_Grip_All', 'Y2A_Grip_All', 'Y3A_Grip_All', 'Y1A_BW_BW', 'Y2A_BW_BW', 'Y3A_BW_BW', 'Y1_Glu.F_Glucose', 'Y2_Glu.F_Glucose', 'Y3_Glu.F_Glucose', 'Y1_Echo_BPM', 'Y2_Echo_BPM', 'Y3_Echo_BPM', 'Y1_Echo_CardiacOutput', 'Y2_Echo_CardiacOutput', 'Y3_Echo_CardiacOutput', 'Y1_AS_MeanLog', 'Y2_AS_MeanLog', 'Y3_AS_MeanLog','Y1A_Frailty_FrailtyAdj', 'Y2A_Frailty_FrailtyAdj', 'Y3A_Frailty_FrailtyAdj']
train_df.loc[:, latent_columns] = scaler.fit_transform(train_df[latent_columns])
test_df.loc[:, latent_columns] = scaler.fit_transform(test_df[latent_columns])
X_train_tensor = torch.tensor(train_df[latent_columns + ['labels']].values, dtype=torch.float32)
y_train_tensor = torch.tensor(train_df[label_col].values, dtype=torch.float32)
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
X_test_tensor = torch.tensor(test_df[latent_columns + ['labels']].values, dtype=torch.float32)
y_test_tensor = torch.tensor(test_df[label_col].values, dtype=torch.float32)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [58]:
train_df[latent_columns].values

array([[-0.02834937,  0.29676135,  1.09527655,  0.34268266, -0.70953926],
       [-1.16612949,  0.85662647,  0.89702632,  1.4477382 ,  0.37222222],
       [ 1.14492009, -0.78444516, -0.70612887,  1.34791154,  1.19990708],
       ...,
       [-1.60339003, -0.79342877, -1.18813162,  0.45600116,  0.69563052],
       [ 0.22521736,  0.98616254, -0.417128  , -0.08488338,  0.81619884],
       [-0.13986785, -2.09606235, -0.80412499, -0.59127203,  1.43038225]])

In [60]:
data, labels = next(iter(test_loader))

In [61]:
data

tensor([[-1.1065, -1.6996,  1.7953, -0.8324, -1.5509,  0.0000],
        [ 0.2830,  0.0912, -1.6155, -1.4426,  0.7682,  4.0000],
        [ 0.5298,  0.0727,  0.6764, -2.4226, -0.2374,  4.0000],
        [ 1.5640, -1.6555, -0.8094, -0.9288,  1.4199,  0.0000],
        [ 0.6268, -1.1022, -1.3896,  0.0244, -0.9917,  0.0000],
        [ 1.3638,  1.3792, -0.1144,  0.5146, -0.1126,  3.0000],
        [ 1.1151, -0.9370,  0.3119, -0.5102, -0.3840,  1.0000],
        [-0.5877, -0.6992,  0.2393,  0.1154,  0.7774,  1.0000],
        [-0.0892,  1.0443, -0.8551,  0.9104, -0.8637,  4.0000],
        [ 1.8578, -0.6403,  1.0154,  0.2525, -1.0751,  4.0000],
        [ 0.5633, -0.4512,  0.1777,  0.2791, -0.2916,  4.0000],
        [ 0.7262, -0.3839, -0.0354, -1.1339, -0.7022,  4.0000],
        [-0.6617, -1.4363,  0.4181, -0.9626,  0.7959,  1.0000],
        [ 0.0266, -0.9648, -1.4214, -0.1691,  0.9173,  0.0000],
        [-0.2752, -1.0943,  1.0327, -0.4696, -0.7831,  4.0000],
        [ 0.4861, -0.7213, -1.5960, -0.4