In [2]:
M = 5
print([[None for num in range(M)] for num in range(M)])

[[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]]


In [3]:
import torch

In [4]:
train_ids_mnist = torch.load('data/train-ms-mnist-idx.pt', map_location='cpu')

print(train_ids_mnist)
print(train_ids_mnist.shape)

tensor([13126, 41465, 40915,  ..., 27902, 27110,  3447])
torch.Size([1682040])


In [5]:
test_ids_mnist = torch.load('data/test-ms-mnist-idx.pt', map_location='cpu')

print(test_ids_mnist)
print(test_ids_mnist.shape)

tensor([3251, 1843,  592,  ...,   73, 4325, 3874])
torch.Size([300000])


In [6]:
test_ids_svhn = torch.load('data/test-ms-svhn-idx.pt', map_location='cpu')

print(test_ids_svhn)
print(test_ids_svhn.shape)

tensor([ 3720, 10453,  5970,  ...,  9035, 23181, 25393])
torch.Size([300000])


In [7]:
train_ids_svhn = torch.load('data/train-ms-svhn-idx.pt', map_location='cpu')

print(train_ids_svhn)
print(train_ids_svhn.shape)

tensor([65611, 53126, 57399,  ..., 58460, 46857, 47680])
torch.Size([1682040])


In [8]:
from data_builder import*

In [9]:
# testing dataloader function for join datasets 
batch_size = 128
train_loader, test_loader = getDataLoaders(batch_size=batch_size, shuffle=True, device='cuda')

In [10]:
first_iter = next(iter(train_loader))
print(len(first_iter))

2


In [11]:
first_iter[0][0].shape

torch.Size([128, 1, 28, 28])

In [12]:
first_iter[1][0].shape

torch.Size([128, 3, 32, 32])

In [13]:
first_iter[1][1].shape

torch.Size([128])

In [14]:
first_iter[1][1].shape

torch.Size([128])

In [20]:
first_iter[0][1]

tensor([5, 3, 3, 3, 5, 3, 0, 2, 2, 3, 7, 5, 2, 5, 3, 2, 2, 2, 1, 7, 1, 4, 8, 2,
        4, 0, 3, 7, 9, 5, 3, 1, 0, 0, 4, 9, 0, 6, 7, 8, 2, 3, 5, 2, 7, 5, 3, 7,
        8, 6, 6, 1, 8, 9, 1, 6, 4, 6, 7, 7, 7, 9, 9, 7, 9, 2, 0, 3, 7, 5, 5, 8,
        4, 1, 8, 3, 1, 5, 5, 2, 0, 6, 2, 7, 8, 2, 9, 2, 4, 9, 6, 8, 9, 1, 8, 8,
        7, 6, 3, 5, 4, 3, 2, 8, 3, 5, 2, 3, 7, 1, 1, 6, 1, 5, 3, 4, 8, 6, 2, 2,
        7, 4, 7, 4, 7, 5, 5, 4])

In [19]:
first_iter[1][1]

tensor([5, 3, 3, 3, 5, 3, 0, 2, 2, 3, 7, 5, 2, 5, 3, 2, 2, 2, 1, 7, 1, 4, 8, 2,
        4, 0, 3, 7, 9, 5, 3, 1, 0, 0, 4, 9, 0, 6, 7, 8, 2, 3, 5, 2, 7, 5, 3, 7,
        8, 6, 6, 1, 8, 9, 1, 6, 4, 6, 7, 7, 7, 9, 9, 7, 9, 2, 0, 3, 7, 5, 5, 8,
        4, 1, 8, 3, 1, 5, 5, 2, 0, 6, 2, 7, 8, 2, 9, 2, 4, 9, 6, 8, 9, 1, 8, 8,
        7, 6, 3, 5, 4, 3, 2, 8, 3, 5, 2, 3, 7, 1, 1, 6, 1, 5, 3, 4, 8, 6, 2, 2,
        7, 4, 7, 4, 7, 5, 5, 4])

In [15]:
len(train_loader)

13141

In [16]:
len(test_loader)

2344

In [17]:
epoch = 100
step = int(epoch / 5)
print(step, step * 2, step * 3, step * 4, step * 5)

20 40 60 80 100
